name: cv-lit
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - cpuonly # Or cudatoolkit if GPU is available, but cpuonly is safer for general use
  - opencv
  - numpy
  - gdal
  - pyproj
  - shapely
  - geopandas
  - requests
  - pip
  - pip:
    - segment-anything
